openapi: 3.0.0
info:
  title: Employer Controller API
  description: API endpoints for employer management
  version: 1.0.0
paths:
  /employer/register:
    post:
      summary: Register an employer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employer'
      responses:
        '201':
          description: Employer registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployerDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /employer/offer/all:
    get:
      summary: Get all job offers for an employer
      parameters:
        - in: query
          name: employerId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved job offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOfferDTO'
        '500':
          description: Internal Server Error
  /employer/offer:
    post:
      summary: Add a new job offer for an employer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobOfferDTO'
      parameters:
        - in: query
          name: employerId
          required: true
          schema:
            type: integer
      responses:
        '202':
          description: Job offer added successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /employer/offer/{id}:
    put:
      summary: Update a job offer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobOfferDTO'
      responses:
        '202':
          description: Job offer updated successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      summary: Delete a job offer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '202':
          description: Job offer deleted successfully
        '500':
          description: Internal Server Error
components:
  schemas:
    Employer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Employer's ID
        firstName:
          type: string
          description: Employer's first name
        lastName:
          type: string
          description: Employer's last name
        email:
          type: string
          description: Employer's email
        organisationName:
          type: string
          description: Employer's organization name
        organisationPhone:
          type: string
          description: Employer's organization phone number
        jobOffers:
          type: array
          items:
            $ref: '#/components/schemas/JobOfferDTO'
          description: List of job offers associated with the employer


    EmployerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Employer's ID
        firstName:
          type: string
          description: Employer's first name
        lastName:
          type: string
          description: Employer's last name
        email:
          type: string
          description: Employer's email
        role:
          type: string
          description: Employer's role
        organisationName:
          type: string
          description: Employer's organization name
        organisationPhone:
          type: string
          description: Employer's organization phone number
        jobOffers:
          type: array
          items:
            $ref: '#/components/schemas/JobOfferDTO'
          description: List of job offers associated with the employer


    JobOfferDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Job Offer's ID
        title:
          type: string
          description: Job Offer's title
        department:
          type: string
          description: Job Offer's department
        location:
          type: string
          description: Job Offer's location
        description:
          type: string
          description: Job Offer's description
        salary:
          type: number
          format: float
          description: Job Offer's salary
        startDate:
          type: string
          format: date-time
          description: Job Offer's start date
        duration:
          type: integer
          description: Job Offer's duration in weeks
        expirationDate:
          type: string
          format: date-time
          description: Job Offer's expiration date
        offreState:
          type: string
          description: Job Offer's state
        hoursPerWeek:
          type: integer
          description: Job Offer's hours per week
