swagger: '2.0'
info:
  title: Employer Controller API
  description: API documentation for the Employer Controller
  version: 1.0.0
basePath: /v1  # Replace with your actual API version and base path
schemes:
  - http
  - https
paths:
  /employer/register:
    post:
      tags:
        - Employer
      summary: Register an employer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: employerDTO
          description: Employer registration details
          required: true
          schema:
            $ref: '#/definitions/RegisterEmployerDTO'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/EmployerDTO'
        400:
          description: Bad Request
          schema:
            type: string
        500:
          description: Internal Server Error
          schema:
            type: string

  /employer/offer/all:
    get:
      tags:
        - Employer
      summary: Get all job offers for an employer
      produces:
        - application/json
      parameters:
        - in: query
          name: employerId
          description: ID of the employer
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/JobOfferDTO'
        500:
          description: Internal Server Error
          schema:
            type: string

  /employer/offer:
    post:
      tags:
        - Employer
      summary: Add a new job offer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: jobOffer
          description: Job offer details
          required: true
          schema:
            $ref: '#/definitions/JobOfferDTO'
        - in: body
          name: employerId
          description: ID of the employer
          required: true
          type: integer
      responses:
        202:
          description: Accepted
        400:
          description: Bad Request
          schema:
            type: string
        500:
          description: Internal Server Error
          schema:
            type: string

  /employer/offer/update:
    put:
      tags:
        - Employer
      summary: Update a job offer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: jobOffer
          description: Updated job offer details
          required: true
          schema:
            $ref: '#/definitions/JobOfferDTO'
      responses:
        202:
          description: Accepted
        400:
          description: Bad Request
          schema:
            type: string
        500:
          description: Internal Server Error
          schema:
            type: string

  /employer/offer/{id}:
    delete:
      tags:
        - Employer
      summary: Delete a job offer by ID
      parameters:
        - in: path
          name: id
          description: ID of the job offer to delete
          required: true
          type: integer
      responses:
        202:
          description: Accepted
        500:
          description: Internal Server Error
          schema:
            type: string

definitions:
    Employer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Employer's ID
        firstName:
          type: string
          description: Employer's first name
        lastName:
          type: string
          description: Employer's last name
        email:
          type: string
          description: Employer's email
        organisationName:
          type: string
          description: Employer's organization name
        organisationPhone:
          type: string
          description: Employer's organization phone number
        jobOffers:
          type: array
          items:
            $ref: '#/definitions/JobOfferDTO'
          description: List of job offers associated with the employer


    EmployerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Employer's ID
        firstName:
          type: string
          description: Employer's first name
        lastName:
          type: string
          description: Employer's last name
        email:
          type: string
          description: Employer's email
        role:
          type: string
          description: Employer's role
        organisationName:
          type: string
          description: Employer's organization name
        organisationPhone:
          type: string
          description: Employer's organization phone number
        jobOffers:
          type: array
          items:
            $ref: '#/definitions/JobOfferDTO'
          description: List of job offers associated with the employer


    JobOfferDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Job Offer's ID
        title:
          type: string
          description: Job Offer's title
        department:
          type: string
          description: Job Offer's department
        location:
          type: string
          description: Job Offer's location
        description:
          type: string
          description: Job Offer's description
        salary:
          type: number
          format: float
          description: Job Offer's salary
        startDate:
          type: string
          format: date-time
          description: Job Offer's start date
        duration:
          type: integer
          description: Job Offer's duration in weeks
        expirationDate:
          type: string
          format: date-time
          description: Job Offer's expiration date
        offreState:
          type: string
          description: Job Offer's state
        hoursPerWeek:
          type: integer
          description: Job Offer's hours per week
    RegisterEmployerDTO:
      type: object
      properties:
        registerDTO:
          $ref: '#/definitions/RegisterDTO'
        employerDTO:
          $ref: '#/definitions/EmployerDTO'

    RegisterDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        role:
          type: string