openapi: 3.0.0
info:
  title: Manager Controller API
  description: API endpoints for managing job offers
  version: 1.0.0
paths:
  /manager/jobOffers/all:
    get:
      summary: Get all job offers
      responses:
        '200':
          description: Successfully retrieved job offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOfferDTO'
        '500':
          description: Internal Server Error
  /manager/jobOffer/{id}:
    get:
      summary: Get job offer by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Job offer ID
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved job offer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobOfferDTO'
        '404':
          description: Job offer not found
        '500':
          description: Internal Server Error
  /manager/jobOffers/{employerId}:
    get:
      summary: Get job offers by employer ID
      parameters:
        - in: path
          name: employerId
          required: true
          description: Employer ID
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved job offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOfferDTO'
        '404':
          description: Employer not found
        '500':
          description: Internal Server Error
  /manager/jobOffers/submitted:
    get:
      summary: Get submitted job offers
      responses:
        '200':
          description: Successfully retrieved submitted job offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOfferDTO'
        '500':
          description: Internal Server Error
  /manager/jobOffers/accepted:
    get:
      summary: Get accepted job offers
      responses:
        '200':
          description: Successfully retrieved accepted job offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOfferDTO'
        '500':
          description: Internal Server Error
  /manager/jobOffers/refused:
    get:
      summary: Get refused job offers
      responses:
        '200':
          description: Successfully retrieved refused job offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOfferDTO'
        '500':
          description: Internal Server Error
components:
  schemas:
    JobOfferDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Job Offer's ID
        title:
          type: string
          description: Job Offer's title
        department:
          type: string
          description: Job Offer's department
        location:
          type: string
          description: Job Offer's location
        description:
          type: string
          description: Job Offer's description
        salary:
          type: number
          format: float
          description: Job Offer's salary
        startDate:
          type: string
          format: date-time
          description: Job Offer's start date
        duration:
          type: integer
          description: Job Offer's duration in weeks
        expirationDate:
          type: string
          format: date-time
          description: Job Offer's expiration date
        offreState:
          type: string
          description: Job Offer's state
        hoursPerWeek:
          type: integer
          description: Job Offer's hours per week