swagger: '2.0'
info:
  title: Student Controller API
  description: API endpoints for student operations
  version: 1.0.0
basePath: /student
schemes:
  - http
host: localhost:3000  # Update with your actual host and port
produces:
  - application/json
paths:
  /register:
    post:
      summary: Register a student
      consumes:
        - application/json
      parameters:
        - in: body
          name: student
          schema:
            $ref: '#/definitions/RegisterStudentDTO'
      responses:
        '201':
          description: Student registered successfully
          schema:
            $ref: '#/definitions/StudentDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /cv/{studentId}:
    post:
      summary: Upload a CV for a student
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: studentId
          required: true
          type: integer
        - in: formData
          name: file
          type: file
          required: true
      responses:
        '202':
          description: CV uploaded successfully
          schema:
            $ref: '#/definitions/CvFileDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    delete:
      summary: Delete a student's CV
      parameters:
        - in: path
          name: studentId
          required: true
          type: integer
      responses:
        '202':
          description: CV deleted successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

definitions:
  RegisterStudentDTO:
    type: object
    properties:
      email:
        type: string
        description: Student's email
      password:
        type: string
        description: Student's password
      role:
        type: string
        description: Student's role

  StudentDTO:
    type: object
    properties:
    # Define your StudentDTO properties here

  CvFileDTO:
    type: object
    properties:
      id:
        type: integer
        description: CV File's ID
      fileName:
        type: string
        description: CV File's name
      fileData:
        type: string
        format: binary
        description: CV File's binary data
      cvState:
        type: string
        description: CV File's state
