swagger: '2.0'
info:
  title: User Controller API
  description: API documentation for the User Controller
  version: 1.0.0
basePath: /
schemes:
  - http
  - https
paths:
  /user/login:
    post:
      tags:
        - User
      summary: Login a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loginDTO
          description: Login credentials
          required: true
          schema:
            $ref: '#/definitions/LoginDTO'
      responses:
        202:
          description: Accepted
          schema:
            $ref: '#/definitions/UserDTO'
        400:
          description: Bad Request
          schema:
            type: string
        500:
          description: Internal Server Error
          schema:
            type: string
definitions:
    LoginDTO:
      type: object
      properties:
        email:
          type: string
          description: User's email
        password:
          type: string
          description: User's password

    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: User's ID
        firstName:
          type: string
          description: User's first name
        lastName:
          type: string
          description: User's last name
        email:
          type: string
          description: User's email
        role:
          type: string
          description: User's role
