openapi: 3.0.0
info:
  title: User Controller API
  description: API endpoints for user management
  version: 1.0.0
paths:
  /user:
    post:
      summary: Register a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDTO'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /user/login:
    post:
      summary: Login as a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDTO'
      responses:
        '202':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    RegisterDTO:
      type: object
      properties:
        email:
          type: string
          description: User's email
        password:
          type: string
          description: User's password
        role:
          type: string
          description: User's role

    LoginDTO:
      type: object
      properties:
        email:
          type: string
          description: User's email
        password:
          type: string
          description: User's password

    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: User's ID
        firstName:
          type: string
          description: User's first name
        lastName:
          type: string
          description: User's last name
        email:
          type: string
          description: User's email
        role:
          type: string
          description: User's role
